name: URL File Sync

on:
  repository_dispatch:
    types: [url-filesync]

jobs:
  provide_matrix_json:
    name: Provide Matrix JSON
    runs-on: ubuntu-latest
    steps:
      - name: Get Matrix Payload
        id: matrix
        run: echo "::set-output name=value::${{ toJSON(github.event.client_payload.matrix) }}"
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
  url_filesync:
    name: URL File Sync - ${{ matrix.dst_path }}
    needs: provide_matrix_json
    strategy:
      matrix: ${{ fromJson(needs.provide_matrix_json.outputs.matrix) }}
    runs-on: ubuntu-latest
    env:
      dst_token: ${{ secrets.GH_PAT }}
    steps:
      - name: Setup Environment Variables
        run: |
          ## Change it with defined client payload
          
          ghw_password="${{ github.event.client_payload.ghw_password }}"
          if [[ -n "$ghw_password" ]]; then
              echo "::add-mask::$ghw_password"
          fi
          if [[ "$ghw_password" != "${{ secrets.GHW_PASSWORD }}" ]]; then
              echo "dst_token=null" >> $GITHUB_ENV
          fi
          
          # DST_TOKEN
          dst_token="${{ github.event.client_payload.dst_token }}"
          if [[ -n "$dst_token" ]]; then
              echo "::add-mask::$dst_token"
              echo "dst_token=$dst_token" >> $GITHUB_ENV
          fi
          # SRC_URL
          src_url="${{ matrix.src_url }}"
          if [[ -n "$src_url" ]]; then
              echo "src_uri=$src_url" >> $GITHUB_ENV
          fi
          # SRC_TOKEN
          src_token="${{ matrix.src_token }}"
          if [[ -n "$src_token" ]]; then
              echo "::add-mask::$src_token"
              src_url="-H 'Authorization: token $src_token' $src_url"
              echo "src_uri=$src_url" >> $GITHUB_ENV
          fi
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.client_payload.dst_repository }}
          token: ${{ env.dst_token }}
      - name: URL File Sync
        run: curl ${{ env.src_uri }} -o ${{ matrix.dst_path }}
      - name: Commit and Push
        run: |
          git config user.email "actions@github.com"
          git config user.name "GHWorkflow - URL File Sync"
          git add --all
          git commit -m "Update file" -m "${{ matrix.dst_path }}" || echo "No changes to commit"
          git push